[general]
library_name = "libclingo"
output_file_path = "./LibClingo.jl"
module_name = "LibClingo"
use_julia_native_enum_type = true
use_deterministic_symbol = true

[codegen]
opaque_as_mutable_struct = true

[codegen.macro]
macro_mode = "basic"